### ISSUE TITLE
Model file not found

### ISSUE THREAD

**Issue by shihabtechno** [AI4Bharat/IndicWav2Vec#17]
return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/ULCA_Compliance/app/support.py", line 238, in load_model
    mdl, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([mdl_path])
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/venv/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 278, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: /new_disk/models/bn/bn.pt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/flask_api.py", line 28, in <module>
    model, dictionary = load_model(m['model_path'])
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/ULCA_Compliance/app/support.py", line 243, in load_model
    m = torch.load(mdl_path)
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/venv/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/venv/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shihab/Projects/indicwav2back/IndicWav2Vec/venv/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/new_disk/models/bn/bn.pt'

**Comment by tahirjmakhdoomi** [comment]
Hi [shihabtechno]

There should be a json file containing paths to your model checkpoints. You will need to update your model paths there.
